const eventosPadrao = [
    {
        id: 1,
        title: 'Implementação de Projetos ',
        start: new Date(2024, 10, 27, 18, 40),
        end: new Date(2024, 10, 27, 21, 40),
        desc: 'Disciplina - Implementação de Projetos - Docente - Washington Luis Souza da Anunciação',
        color: 'blue',
        tipo: 'Aula',
    },
     {
        id: 2,
        title: 'Planejamento de Sistemas',
        start: new Date(2024, 10, 3, 18, 40),
        end: new Date(2024, 10, 3, 21, 40),
        desc: 'Docente: Maria Clara Silva',
        color: 'green',
        tipo: 'Aula',
    },
    {
        id: 3,
        title: 'Desenvolvimento Ágil',
        start: new Date(2024, 10, 6, 18, 40),
        end: new Date(2024, 10, 6, 21, 40),
        desc: 'Docente: João Carlos Mendes',
        color: 'red',
        tipo: 'Aula',
    },
    {
        id: 4,
        title: 'Gestão de Projetos',
        start: new Date(2024, 10, 8, 18, 40),
        end: new Date(2024, 10, 8, 21, 40),
        desc: 'Docente: Paula Costa',
        color: 'orange',
        tipo: 'Aula',
    },
    {
        id: 5,
        title: 'Metodologias de Pesquisa',
        start: new Date(2024, 10, 10, 18, 40),
        end: new Date(2024, 10, 10, 21, 40),
        desc: 'Docente: Carlos Almeida',
        color: 'purple',
        tipo: 'Aula',
    },
    {
        id: 6,
        title: 'Revisão Geral',
        start: new Date(2024, 10, 13, 18, 40),
        end: new Date(2024, 10, 13, 21, 40),
        desc: 'Docente: Ana Luiza Martins',
        color: 'blue',
        tipo: 'Aula',
    },
    {
        id: 7,
        title: 'Workshop de Inovação',
        start: new Date(2024, 10, 15, 18, 40),
        end: new Date(2024, 10, 15, 21, 40),
        desc: 'Docente: Felipe Souza',
        color: 'cyan',
        tipo: 'Aula',
    },
    {
        id: 8,
        title: 'Entregas de Projeto',
        start: new Date(2024, 10, 17, 18, 40),
        end: new Date(2024, 10, 17, 21, 40),
        desc: 'Docente: Washington Luis Souza da Anunciação',
        color: 'blue',
        tipo: 'Aula',
    },
    {
        id: 9,
        title: 'Encerramento de Semestre',
        start: new Date(2024, 10, 20, 18, 40),
        end: new Date(2024, 10, 20, 21, 40),
        desc: 'Docente: Maria Clara Silva',
        color: 'green',
        tipo: 'Aula',
    },
    {
        id: 10,
        title: 'Reunião de Avaliação',
        start: new Date(2024, 10, 22, 18, 40),
        end: new Date(2024, 10, 22, 21, 40),
        desc: 'Docente: João Carlos Mendes',
        color: 'red',
        tipo: 'Aula',
    },
]

export default eventosPadrao;